services:
  api-dev:
    image: node:22-alpine
    working_dir: /app
    env_file: .env
    volumes:
      - .:/app        # monta todo o seu projeto
      - /app/node_modules  # para não sobrescrever os node_modules do container
    ports:
      - '3000:3000'
    command: >
      sh -c "npm ci &&
             npm run start:dev"
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
